routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Route::get('/about-us', 'PagesController@about');
Route::get('/contact-us', 'PagesController@contact');
Route::post('/contact-us', 'PagesController@send_inquiry')->name('contact-us');
Route::get('/terms-of-use', 'PagesController@terms_use');
Route::get('/privacy-policy', 'PagesController@privacy_policy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('logout', function(){
	Auth::logout(); //logout the current user
	Session::flush(); //delete the session
	Cache::flush();
	return Redirect::to('login'); //redirect to login page
})->name('logout');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']] , function(){
	// HomeController Related to profile
	Route::get('/', 'Admin\HomeController@index');	
	Route::get('/dashboard', 'Admin\HomeController@index')->name('dashboard');	
	Route::get('/profile', 'Admin\HomeController@profile')->name('profile');
	Route::post('/profile', 'Admin\HomeController@updateProfile')->name('updateProfile');
	Route::post('/update_email', 'Admin\HomeController@updateEmail');
	Route::get('/update_email', 'Admin\HomeController@updateEmailView')->name('admin_change_email');
	Route::post('/change_password', 'Admin\HomeController@changePassword');
	Route::get('/change_password', 'Admin\HomeController@changePasswordView')->name('admin_change_password');
	
	Route::get('/resetPwd', 'Admin\HomeController@resetPwd');

	// UserController Related to users detail
	Route::resource('user', 'Admin\UserController');
	Route::post('user/update_status', 'Admin\UserController@update_status');

	// EmailController Related to Email template
	Route::resource('email', 'Admin\EmailController');

	// CmsController related to Cms 
	Route::resource('cms', 'Admin\CmsController');
	Route::post('cms/update_status', 'Admin\CmsController@update_status');
	
	Route::get('social', 'Admin\SocialController@index')->name('social');
	Route::post('social', 'Admin\SocialController@update');

	Route::get('company-details', 'Admin\BasicController@view_company_details')->name('company-details');
	Route::delete('company-details', 'Admin\BasicController@update_company_details')->name('update-company-details');
	Route::post('company-details/{type}', 'Admin\BasicController@save_company_details')->name('save-company-details');


	Route::resource('inquiry', 'Admin\InquiryController');
	Route::resource('config','Admin\ConfigurationController',['only' => [
		'index', 'store'
	]]);

	// Testimonials
	Route::resource('testimonials', 'Admin\TestimonialController');
	Route::get('/testimonials/{id}/delete_image', 'Admin\TestimonialController@destroyImage');
	Route::get('/testimonials/update_status/{id}/{status}', [
		'as' => 'testimonial.status',
		'uses' => 'Admin\TestimonialController@updateStatus',
	]);
	Route::delete('/testimonials/destroy/{id}', 'Admin\TestimonialController@destroy');
	Route::post('testimonials/{id}/edit', 'Admin\TestimonialController@update');

});

Route::group(['middleware' => 'auth'] , function(){
	Route::get('/profile', 'ProfileController@index')->name('profile');
	Route::post('/profile-update', 'ProfileController@updateProfile')->name('profile_update');
	Route::get('/change-password', 'ProfileController@changePasswordView');
	Route::post('/change-password', 'ProfileController@changePassword')->name('change-password');
	Route::get('/resetpassword-confirmation', 'ProfileController@confirmResetpassword')->name('checkreset');
});

Route::get('/joinuser/{id}', 'JoinUserController@index');
Route::post('/joinuser/create' , 'JoinUserController@join')->name('joinuser.create');


// to confirm account
Route::get('register/confirm/{user_id}', 'Auth\RegisterController@confirm');
Route::post('register/change-email/{user_id}', 'Auth\RegisterController@changeEmail')->name('change-email');

// to verify email
Route::get('register/verify/{confirmationCode}', 'Auth\VerifyController@verify');
Route::post('register/verify/', 'Auth\VerifyController@verify')->name('register_verify');

Route::get('register/resend/{user_id}', 'Controller@resendVerification')->name('resendverification');

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.layout')

@section('styles')
<style type="text/css">
	span.info-box-number a {
		font-weight: normal;
		font-size: 15px;
	}
	.customheight{
		height: 104px;
	}
</style>
@endsection
@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Dashboard
			<small><!-- Version 2.0 --></small>
		</h1>
		<ol class="breadcrumb">
			<li class="active"><i class="fa fa-dashboard"></i> Home</li>
		</ol>
	</section>

	<!-- Main content -->
	<section class="content">
		<!-- Info boxes -->
		<div class="row">
			<div class="col-md-4 col-sm-6 col-xs-12">
				<div class="info-box">
					<span class="info-box-icon bg-aqua"><i class="fa fa-user"></i></span>

					<div class="info-box-content">
						<span class="info-box-text">Manage Users</span>
						<span class="info-box-number"><a href="{{ route('user.index') }}">Users List</a></span>
						<span class="info-box-number"><a href="{{ route('user.create') }}"> Add Users</a></span>
					</div>
					<!-- /.info-box-content -->
				</div>
				<!-- /.info-box -->
			</div>
			<!-- /.col -->
			<div class="col-md-4 col-sm-6 col-xs-12">
				<div class="info-box">
					<span class="info-box-icon bg-yellow"><i class="fa fa-envelope"></i></span>

					<div class="info-box-content">
						<span class="info-box-text">Manage Emails</span>
						<span class="info-box-number"><a href="{{ route('email.index') }}">Email Templates</a></span>

					</div>
					<!-- /.info-box-content -->
				</div>
				<!-- /.info-box -->
			</div>
			<!-- /.col -->
			<div class="col-md-4 col-sm-6 col-xs-12">
				<div class="info-box">
					<span class="info-box-icon bg-green customheight"><i class="fa fa-gears"></i></span>

					<div class="info-box-content">
						<span class="info-box-text">Manage CMS</span>
						<span class="info-box-number"><a href="{{ route('cms.index') }}">Cms List</a></span>
						<span class="info-box-number"><a href="{{ route('social') }}"> Social Networks </a></span>
						<span class="info-box-number"><a href="{{ route('company-details') }}"> Company Details </a></span>
					</div>
					<!-- /.info-box-content -->
				</div>
				<!-- /.info-box -->
				</div>
				<div class="col-md-4 col-sm-6 col-xs-12">
				<div class="info-box">
					<span class="info-box-icon bg-blue"><i class="fa fa-gears"></i></span>

					<div class="info-box-content">
						<span class="info-box-text">Manage Inquiry</span>
						<span class="info-box-number"><a href="{{ route('inquiry.index') }}">Inquiries List</a></span>						
					</div>
					<!-- /.info-box-content -->
				</div>
				<!-- /.info-box -->
			</div>
				
			

		</div>
		<!-- /.row -->

	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->

@endsection

resources/views/admin/profile.blade.php
@extends('admin.layouts.layout')
@section('content')

<!-- Content Wrapper. Cont•••••ains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
	  	<h1>
			Admin Profile
			<small>Admin Profile Informations</small>
	  	</h1>
	  	<ol class="breadcrumb">
			<li><a href="{!! url('admin/dashboard') !!}"><i class="fa fa-dashboard"></i> Home</a></li>
			<li class="active">Admin Profile</li>
	  	</ol>
	</section>

	<!-- Main content -->
	<section class="content">
	  	<!-- Info boxes -->
	  	<div class="row">
	  	
			<div class="col-md-12 col-md-8">
	  		<div class="box box-info">
			
			<div class="box-header with-border">
				@include('admin.partials.errors')
			</div>
					
			<form role="form" method="post" action="{{ route('updateProfile') }}">
			  	{{ csrf_field() }}

			    <div class="box-body">
			    	<div class="form-group pull-right">
					  	<a href="javascript:void(0);" onclick="changePassword()" class="btn btn-primary">Change Password</a>

					  	<a href="javascript:void(0);" onclick="changeEmail()" class="btn btn-primary">Change Email</a>
				 	</div>
				 	<div class="clearfix"></div>

				   	<div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
				  		<label for="firstname" class="required">First Name </label>

					  	<input type="text" class="form-control" id="name" name="first_name" placeholder="First name" maxlength="40" value="{{ old('first_name', $user->first_name) }}">
				  		
				  		@if ($errors->has('first_name'))
						  	@foreach ($errors->get('first_name') as $msg) 
								<span class="help-block">
									<strong>{{ $msg }}</strong>
								</span>
						  	@endforeach
						@endif
					</div>

					<div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
			            <label for="lname" class="control-label">Last Name</label>

			            <input id="lname"  placeholder="Last Name"  type="text" class="form-control" name="last_name" value="{{ old('last_name', $user->last_name) }}" maxlength="25">

					  	@if ($errors->has('last_name'))
						  	<span class="help-block">
								<strong>{{ $errors->first('last_name') }}</strong>
						  	</span>
					  	@endif
			        </div>

				    <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
			            <label for="username" class="control-label required">Username</label>

		                <input id="username" type="text" class="form-control" name="username" value="{{ old('username', $user->username) }}" maxlength="25" placeholder="User Name" >

		                @if ($errors->has('username'))
		                    <span class="help-block">
		                        <strong>{{ $errors->first('username') }}</strong>
		                    </span>
		                @endif
			        </div>

					<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
						<label for="email" class="control-label required">Email</label>
						
					  	<input id="email" type="text" class="form-control" name="email" value="{{ old('email', $user->email) }}"  placeholder="Email" maxlength="100" readonly>

					  	@if ($errors->has('email'))
						  	<span class="help-block">
								<strong>{{ $errors->first('email') }}</strong>
						  	</span>
					  	@endif
					</div>

					<div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
						<label for="tel" class="control-label">Phone Number</label>

				   		<input type="tel" maxlength="12" class="form-control" name="phone" id="phone" value="{{ old('phone', $user->phone) }}" >

				   		 <input type="hidden" name="phone_code" id="co-code" value="{{ old('phone_code', $user->phone_code)!== null ? $user->phone_code : '1' }}">
				   		
				   		 @if ($errors->has('phone'))
						  	<span class="help-block">
								<strong>{{ $errors->first('phone') }}</strong>
						  	</span>
					  	@endif
				    </div>

			        <div class="form-group{{ $errors->has('dob') ? ' has-error' : ''}}">
                        <label for="dob" class="required control-label">Date Of Birth</label>

                        <input type="text" class="form-control textRead" placeholder="Date Of Birth" name='dob' id="datepicker" autocomplete="off"
                        value="{{ old('dob', show_date($user->user_dob)) }}" readonly>
                        
                        @if ($errors->has('dob'))
                            <span class="help-block">
                                <strong>{{ $errors->first('dob') }}</strong>
                            </span>
                        @endif
                    </div>

	               	<div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
	                    <label for="gender" class="required control-label">Gender</label>

	                    <select class="form-control" name="gender" id="gender">
	                        <option value="m" {{ old('gender') == 'm' ||  $user->gender == "m" ? 'selected' : '' }}>Male</option>
	                        <option value="f" {{ old('gender') == 'f'  ||  $user->gender == "f" ? 'selected' : '' }}>Female</option>
	                        <option value="o" {{ old('gender') == 'o' ||  $user->gender == "o" ? 'selected' : '' }}>Other</option>
	                    </select>

	                    @if ($errors->has('gender'))
	                        <span class="help-block">
	                            <strong>{{ $errors->first('gender') }}</strong>
	                        </span>
	                    @endif
	                </div>

				    <div class="form-group{{ $errors->has('address_one') ? ' has-error' : '' }}">
			            <label for="address_one" class="control-label required">Address Line 1</label>

		                <input type="text" class="form-control" placeholder="Address Line 1" name='address_one' id="address_one"  value="{{ old('address_one', $user->address_one) }}" >
			            
		                @if ($errors->has('address_one'))
		                    <span class="help-block">
		                        <strong>{{ $errors->first('address_one') }}</strong>
		                    </span>
		                @endif
			        </div>

			        <div class="form-group{{ $errors->has('address_two') ? ' has-error' : '' }}">
			            <label for="address_two" class="control-label">Address Line 2</label>

		                <input type="text" class="form-control" placeholder="Address Line 2" name='address_two' id="address_two"  value="{{ old('address_two', $user->address_two) }}" >
		            
		                @if ($errors->has('address_two'))
		                    <span class="help-block">
		                        <strong>{{ $errors->first('address_two') }}</strong>
		                    </span>
		                @endif
			        </div>

				    <div class="form-group{{ $errors->has('google_id') ? ' has-error' : '' 
				     	}}">
						<label for="location" class="control-label required">City/State/Country</label>

						<div class="geo-details">
							<input type="hidden" name="city" data-geo="locality" value="{{ old('city' , $user_city['name']) }}">
							<input type="hidden" name="state" data-geo="administrative_area_level_1" value="{{ old('state', $user_city['state'] ) }}">
							<input type="hidden" name="country" data-geo="country" value="{{ old('country', $user_city['country']) }}">
						</div>

					  	<input id="city_state_country" type="text" class="form-control" name="location" value="{{ old('location' , 
                                    ($user_city['name']!=''? 
                                        ($user_city['name'] == $user_city['state'] ? 
                                            ($user_city['name'] . ', ' . $user_city['country']) : 
                                            ($user_city['name'] . ', ' . $user_city['state'] . ', ' . $user_city['country']
                                        ) 
                                    ) 
                                    : '' )
                                    ) }}" placeholder="Enter a city" maxlength="100"  >


					  	<input type="hidden" name="place_id" id="google_place_id" value="{{ old('place_id', $user_city['google_place_id']) }}"> 
					  	<input type="hidden" name="google_id" id="google_id" value="{{ old('google_id', $user_city['google_id']) }}">  
					  	@if ($errors->has('google_id'))
						  	<span class="help-block">
								<strong>{{ $errors->first('google_id') }}</strong>
						  	</span>
					  	@endif
					</div>

					<div class="form-group{{ $errors->has('zip') ? ' has-error' : '' }}">
		             	
		             	<label for="zip_code" class="control-label required">Zip Code</label>

		                <input type="text" maxlength="6" class="form-control" placeholder="zip code" name='zip' id="zip"  value="{{ old('zip', $user->zip) }}" >
		            
		                @if ($errors->has('zip'))
		                    <span class="help-block">
		                        <strong>{{ $errors->first('zip') }}</strong>
		                    </span>
		                @endif
		            
			        </div>

			  	</div><!-- /.box-body -->
			  	<div class="box-footer">
					<a href="{{ route('dashboard') }}" class="btn btn-default">Cancel</a>
					<button type="submit" class="btn btn-info pull-right">Save</button>
				</div>
			</form>

		  	</div>
			</div>

	  	</div>
	</section>
	<!-- /.content -->
  </div>

  <!-- Model to change Email -->
  <div class="modal fade" id="emailModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Change Email</h4>
        </div>
        <div class="modal-body">
          
        </div>
        
      </div>
      
    </div>
  </div>

  <!-- Model to change password -->

  <div class="modal fade" id="passwordModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Change Password</h4>
        </div>
        <div class="modal-body">
          
          
        </div>
        
      </div>
      
    </div>
  </div>

@endsection

@section('script')
<script src="http://malsup.github.com/jquery.form.js"></script>
<script type="text/javascript">
function changeEmail() {
	$.ajax({
		url : "{{ route('admin_change_email') }}",

		success:function(xhr){
			console.log(xhr);
			$('#emailModal .modal-body').html(xhr);	
		},
	});
	$('#emailModal').modal('show');	
}

function changePassword() {
	$.ajax({
		url : "{{ route('admin_change_password') }}",
		success:function(xhr){
			console.log(xhr);
			$('#passwordModal .modal-body').html(xhr);	
		},
	});
	$('#passwordModal').modal('show');	
}

$(document).on('click', '#submit', function() { 
	$('#emailchange').ajaxSubmit({

	    beforeSubmit: function(){
	    	$('#loading').hide();
	    	$('#emailchange').find('.help-block').remove();
	    	$('#emailchange').closest('.form-group').removeClass('has-error');
	    },
	    success: function (res) {
	        if(res.status==false){
	        	messages = res.message;
	        	jQuery.each(messages, function(index, item) {

	        		if(jQuery.isArray(item)){
	        			jQuery.each(item , function(key , val) {
	        				$('#emailchange').find('#'+index).parent().append('<span class="help-block">'+val+'<strong></span>')
		        		})
	        		}
	        		else {
	        			$('#emailchange').find('#'+index).parent().append('<span class="help-block">'+item+'<strong></span>')
	        		}

				   	$('#emailchange').find('#'+index).closest('.form-group').addClass('has-error');
				});
	        }

	        if(res.status==true)
	        {
	        	$('#loading').show();
	        	window.location.href = "<?php echo url('/admin/profile') ?>";	
	        }
	    },
	    error: function (data) {
	        return false;
	    }
	});
});


$(document).on('click', '#pwdsubmit', function() { 
	$('#passwordChange').ajaxSubmit({

	    beforeSubmit: function(){
	    	$('#passwordChange').find('.help-block').remove();
	    	$('#passwordChange').closest('.form-group').removeClass('has-error');
	    },
	    success: function (res) {
	        if(res.status==false){
	        	messages = res.message;
	        	jQuery.each(messages, function(index, item) {
	        		if(jQuery.isArray(item)){
	        			jQuery.each(item , function(key , val) {
	        				$('#passwordChange').find('#'+index).parent().append('<span class="help-block">'+val+'<strong></span>')
		        		})
	        		}
	        		else {
	        			$('#passwordChange').find('#'+index).parent().append('<span class="help-block">'+item+'<strong></span>')
	        		}

				    $('#passwordChange').find('#'+index).closest('.form-group').addClass('has-error');
				});
	        }

	        if(res.status==true) {
	        	window.location.href = "<?php echo url('/admin/profile') ?>";	
	        }
	    },
	    error: function (data) {
	        return false;
	    }
	});
});

</script>
@endsection