routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Route::get('/about-us', 'PagesController@about');
Route::get('/contact-us', 'PagesController@contact');
Route::post('/contact-us', 'PagesController@send_inquiry')->name('contact-us');
Route::get('/terms-of-use', 'PagesController@terms_use');
Route::get('/privacy-policy', 'PagesController@privacy_policy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('logout', function(){
	Auth::logout(); //logout the current user
	Session::flush(); //delete the session
	Cache::flush();
	return Redirect::to('login'); //redirect to login page
})->name('logout');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']] , function(){
	// HomeController Related to profile
	Route::get('/', 'Admin\HomeController@index');	
	Route::get('/dashboard', 'Admin\HomeController@index')->name('dashboard');	
	Route::get('/profile', 'Admin\HomeController@profile')->name('profile');
	Route::post('/profile', 'Admin\HomeController@updateProfile')->name('updateProfile');
	Route::post('/update_email', 'Admin\HomeController@updateEmail');
	Route::get('/update_email', 'Admin\HomeController@updateEmailView')->name('admin_change_email');
	Route::post('/change_password', 'Admin\HomeController@changePassword');
	Route::get('/change_password', 'Admin\HomeController@changePasswordView')->name('admin_change_password');
	
	Route::get('/resetPwd', 'Admin\HomeController@resetPwd');

	// UserController Related to users detail
	Route::resource('user', 'Admin\UserController');
	Route::post('user/update_status', 'Admin\UserController@update_status');

	// EmailController Related to Email template
	Route::resource('email', 'Admin\EmailController');

	// CmsController related to Cms 
	Route::resource('cms', 'Admin\CmsController');
	Route::post('cms/update_status', 'Admin\CmsController@update_status');
	
	Route::get('social', 'Admin\SocialController@index')->name('social');
	Route::post('social', 'Admin\SocialController@update');

	Route::get('company-details', 'Admin\BasicController@view_company_details')->name('company-details');
	Route::delete('company-details', 'Admin\BasicController@update_company_details')->name('update-company-details');
	Route::post('company-details/{type}', 'Admin\BasicController@save_company_details')->name('save-company-details');


	Route::resource('inquiry', 'Admin\InquiryController');
	Route::resource('config','Admin\ConfigurationController',['only' => [
		'index', 'store'
	]]);

	// Testimonials
	Route::resource('testimonials', 'Admin\TestimonialController');
	Route::get('/testimonials/{id}/delete_image', 'Admin\TestimonialController@destroyImage');
	Route::get('/testimonials/update_status/{id}/{status}', [
		'as' => 'testimonial.status',
		'uses' => 'Admin\TestimonialController@updateStatus',
	]);
	Route::delete('/testimonials/destroy/{id}', 'Admin\TestimonialController@destroy');
	Route::post('testimonials/{id}/edit', 'Admin\TestimonialController@update');

});

Route::group(['middleware' => 'auth'] , function(){
	Route::get('/profile', 'ProfileController@index')->name('profile');
	Route::post('/profile-update', 'ProfileController@updateProfile')->name('profile_update');
	Route::get('/change-password', 'ProfileController@changePasswordView');
	Route::post('/change-password', 'ProfileController@changePassword')->name('change-password');
	Route::get('/resetpassword-confirmation', 'ProfileController@confirmResetpassword')->name('checkreset');
});

Route::get('/joinuser/{id}', 'JoinUserController@index');
Route::post('/joinuser/create' , 'JoinUserController@join')->name('joinuser.create');


// to confirm account
Route::get('register/confirm/{user_id}', 'Auth\RegisterController@confirm');
Route::post('register/change-email/{user_id}', 'Auth\RegisterController@changeEmail')->name('change-email');

// to verify email
Route::get('register/verify/{confirmationCode}', 'Auth\VerifyController@verify');
Route::post('register/verify/', 'Auth\VerifyController@verify')->name('register_verify');

Route::get('register/resend/{user_id}', 'Controller@resendVerification')->name('resendverification');

resources/views/admin/config/index.blade.php
@extends('admin.layouts.layout')
@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Configuration
			<small>Website Setting</small>
		</h1>
		<ol class="breadcrumb">
			<li><a href="{!! url('admin/dashboard') !!}"><i class="fa fa-dashboard"></i> Home</a></li>
			<li class="active">Configuration</li>
		</ol>
	</section>

	<!-- Main content -->
	<section class="content">
		<!-- Info boxes -->
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Update website settings</h3>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						@include('admin.partials.errors')
						<form role="form" method="post" action="{{ route('config.store') }}">
							{{ csrf_field() }}
							<div class="form-group{{ $errors->has('header_script') ? ' has-error' : '' }}">
								<label for="site_description">Header Site Script</label>

								<textarea class="form-control" rows="3" id="header_script" name="header_script" placeholder="Header Site Script">{{$config['header_script']}}</textarea>

								@if ($errors->has('header_script'))
								<span class="help-block">
									<strong>{{ $errors->first('header_script') }}</strong>
								</span>
								@endif
							</div>


							<div class="form-group{{ $errors->has('footer_script') ? ' has-error' : '' }}">
								<label for="site_description">Footer Site Script</label>

								<textarea class="form-control" rows="3" id="footer_script" name="footer_script" placeholder="Footer Site Script">{{$config['footer_script']}}</textarea>

								@if ($errors->has('footer_script'))
								<span class="help-block">
									<strong>{{ $errors->first('footer_script') }}</strong>
								</span>
								@endif
							</div>
							<button type="submit" class="btn btn-info pull-right">Update</button>
						</form>
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>

		</div>
		<!-- /.row -->

	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->

@endsection