routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Route::get('/about-us', 'PagesController@about');
Route::get('/contact-us', 'PagesController@contact');
Route::post('/contact-us', 'PagesController@send_inquiry')->name('contact-us');
Route::get('/terms-of-use', 'PagesController@terms_use');
Route::get('/privacy-policy', 'PagesController@privacy_policy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('logout', function(){
	Auth::logout(); //logout the current user
	Session::flush(); //delete the session
	Cache::flush();
	return Redirect::to('login'); //redirect to login page
})->name('logout');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']] , function(){
	// HomeController Related to profile
	Route::get('/', 'Admin\HomeController@index');	
	Route::get('/dashboard', 'Admin\HomeController@index')->name('dashboard');	
	Route::get('/profile', 'Admin\HomeController@profile')->name('profile');
	Route::post('/profile', 'Admin\HomeController@updateProfile')->name('updateProfile');
	Route::post('/update_email', 'Admin\HomeController@updateEmail');
	Route::get('/update_email', 'Admin\HomeController@updateEmailView')->name('admin_change_email');
	Route::post('/change_password', 'Admin\HomeController@changePassword');
	Route::get('/change_password', 'Admin\HomeController@changePasswordView')->name('admin_change_password');
	
	Route::get('/resetPwd', 'Admin\HomeController@resetPwd');

	// UserController Related to users detail
	Route::resource('user', 'Admin\UserController');
	Route::post('user/update_status', 'Admin\UserController@update_status');

	// EmailController Related to Email template
	Route::resource('email', 'Admin\EmailController');

	// CmsController related to Cms 
	Route::resource('cms', 'Admin\CmsController');
	Route::post('cms/update_status', 'Admin\CmsController@update_status');
	
	Route::get('social', 'Admin\SocialController@index')->name('social');
	Route::post('social', 'Admin\SocialController@update');

	Route::get('company-details', 'Admin\BasicController@view_company_details')->name('company-details');
	Route::delete('company-details', 'Admin\BasicController@update_company_details')->name('update-company-details');
	Route::post('company-details/{type}', 'Admin\BasicController@save_company_details')->name('save-company-details');


	Route::resource('inquiry', 'Admin\InquiryController');
	Route::resource('config','Admin\ConfigurationController',['only' => [
		'index', 'store'
	]]);

	// Testimonials
	Route::resource('testimonials', 'Admin\TestimonialController');
	Route::get('/testimonials/{id}/delete_image', 'Admin\TestimonialController@destroyImage');
	Route::get('/testimonials/update_status/{id}/{status}', [
		'as' => 'testimonial.status',
		'uses' => 'Admin\TestimonialController@updateStatus',
	]);
	Route::delete('/testimonials/destroy/{id}', 'Admin\TestimonialController@destroy');
	Route::post('testimonials/{id}/edit', 'Admin\TestimonialController@update');

});

Route::group(['middleware' => 'auth'] , function(){
	Route::get('/profile', 'ProfileController@index')->name('profile');
	Route::post('/profile-update', 'ProfileController@updateProfile')->name('profile_update');
	Route::get('/change-password', 'ProfileController@changePasswordView');
	Route::post('/change-password', 'ProfileController@changePassword')->name('change-password');
	Route::get('/resetpassword-confirmation', 'ProfileController@confirmResetpassword')->name('checkreset');
});

Route::get('/joinuser/{id}', 'JoinUserController@index');
Route::post('/joinuser/create' , 'JoinUserController@join')->name('joinuser.create');


// to confirm account
Route::get('register/confirm/{user_id}', 'Auth\RegisterController@confirm');
Route::post('register/change-email/{user_id}', 'Auth\RegisterController@changeEmail')->name('change-email');

// to verify email
Route::get('register/verify/{confirmationCode}', 'Auth\VerifyController@verify');
Route::post('register/verify/', 'Auth\VerifyController@verify')->name('register_verify');

Route::get('register/resend/{user_id}', 'Controller@resendVerification')->name('resendverification');

resources/views/admin/partials/adminfooter.blade.php
<footer class="main-footer">
    {!! copyright() !!} 
</footer>

resources/views/admin/partials/adminheader.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="javascript:void(0)" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>Admin</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Admin</b> Panel</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- <img src="{{ asset('admintheme/dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image"> -->
                        <span class="hidden-xs">Administrator <i class="fa fa-angle-down pull-right"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                           <!--  <img src="{{ asset('admintheme/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image"> -->
                            <p>
                                {{ ucfirst(Auth::user()->first_name) }} 
                                {{ ucfirst(Auth::user()->last_name) }}<br>
                                {{ Auth::user()->email }}
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ url('admin/profile') }}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('logout') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/partials/adminsidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- sidebar menu: : style can be found in sidebar.less -->
		<ul class="sidebar-menu">
			<li class="{{ Request::is('admin/dashboard') || Request::is('admin') ? 'active' : '' }}">
				<a href="{!! url('admin/dashboard'); !!}">
					<i class="fa fa-dashboard"></i> <span>Dashboard</span>
					<span class="pull-right-container">
					</span>
				</a>
			</li>

			<li class="treeview {{ Request::is('admin/user') || Request::is('admin/user/*') ? 'active' : '' }}">
				<a href="{!! url('admin/user'); !!}">
					<i class="fa fa-user"></i>
					<span>Manage Users</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li class="{{ Request::is('admin/user') ? 'active' : '' }}">
						<a href="{{ route('user.index') }}"><i class="fa fa-list"></i>Users</a>
					</li>
					
				</ul>
			</li>

			<li class="treeview {{ Request::is('admin/email') || Request::is('admin/email/*') ? 'active' : '' }}">
		  		<a href="#">
					<i class="fa fa-envelope"></i>
					<span>Manage Emails</span>
					<span class="pull-right-container">
			  		<i class="fa fa-angle-left pull-right"></i>
					</span>
		  		</a>
		  		<ul class="treeview-menu">
		  			<li class="{{ Request::is('admin/email') ? 'active' : '' }}">
						<a href="{{ route('email.index') }}"><i class="fa fa-list"></i>Email Templates</a>
					</li>
		  		</ul>
		  	</li>

		  	<li class="treeview {{ Request::is('admin/cms') || Request::is('admin/social') || Request::is('admin/social/*') ||  Request::is('admin/company-details') || Request::is('admin/cms/*') ? 'active' : '' }}">
		  		<a href="#">
		  			<i class="fa fa-gears"></i>
		  			<span>Manage CMS</span>
		  			<span class="pull-right-container">
		  				<i class="fa fa-angle-left pull-right"></i>
		  			</span>
		  		</a>
		  		<ul class="treeview-menu">
		  			<li class="{{ Request::is('admin/cms') ? 'active' : '' }}">
		  				<a href="{{ route('cms.index') }}"><i class="fa fa-list"></i>List</a>
		  			</li>

		  			<li class="{{ Request::is('admin/social') ? 'active' : '' }}">
		  				<a href="{{ route('social') }}"><i class="fa fa-list"></i>Social Networks</a>
		  			</li>

		  			<li class="{{ Request::is('admin/company-details') ? 'active' : '' }}">
		  				<a href="{{ route('company-details') }}"><i class="fa fa-list"></i>Company Details</a>
		  			</li>
		  		</ul>
		  	</li>


		  	<li class="treeview {{ Request::is('admin/inquiry') || Request::is('admin/inquiry/*') ? 'active' : '' }}">
		  		<a href="#">
		  			<i class="fa fa-gears"></i>
		  			<span>Manage Inquiry</span>
		  			<span class="pull-right-container">
		  				<i class="fa fa-angle-left pull-right"></i>
		  			</span>
		  		</a>
		  		<ul class="treeview-menu">
		  			<li class="{{ Request::is('admin/inquiry') ? 'active' : '' }}">
		  				<a href="{{ route('inquiry.index') }}"><i class="fa fa-list"></i>Inquiries</a>
		  			</li>
		  		</ul>
		  	</li>

		  	<li class="treeview {{ Request::is('admin/testimonials/*') || Request::is('admin/testimonials') ? 'active' : '' }}">
		  		<a href="{!! url('admin/testimonials'); !!}">
		  			<i class="fa fa-tags"></i>
		  			<span>Manage Testimonials</span>
		  			<span class="pull-right-container">
		  				<i class="fa fa-angle-left pull-right"></i>
		  			</span>
		  		</a>
		  		<ul class="treeview-menu">
		  			<li class="{{ Request::is('admin/testimonials') || Request::is('admin/testimonials/*') ? 'active' : '' }}"><a href="{{ route('testimonials.index') }}"><i class="fa fa-list"></i> Testimonials List</a></li>
		  		</ul>
		  	</li>

		  	<li class="{{ Request::is('admin/config') ? 'active' : '' }}"><a href="{!! url('admin/config'); !!}"><i class="fa fa-gears"></i> <span>Website Settings</span></a></li>
		  </ul>
		</section>
		<!-- /.sidebar -->
	</aside>

resources/views/admin/partials/controlsidebar.blade.php
<!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->

      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

resources/views/admin/partials/errors.blade.php
<div class="flash-message">
  @foreach (['danger', 'warning', 'success', 'info'] as $msg)
    @if(Session::has('alert-' . $msg))
      <p class="alert alert-{{ $msg }}">{!! Session::get('alert-' . $msg) !!} 
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      </p>
    @endif
  @endforeach
</div> <!-- end .flash-message -->

resources/views/admin/partials/paginition.blade.php
@if ($paging)
	<ul class="pagination">
		{{-- Previous Page Link --}}
        @if ($paging->prev_page_url)
            <li class="disabled"><span>@lang('pagination.previous')</span></li>
        @else
            <li><a href="{{ $paging->prev_page_url }}" rel="prev">@lang('pagination.previous')</a></li>
        @endif
		

		@for($i=$paging->current_page; $i <= $paging->last_page; $i++)
			@if($paging->current_page == $i)
				<li class="active"><a href="#">{{ $i }}</a></li>
			@else
				<li><a href="{{ Request::url() }}?page={{ $i }}">{{ $i }}</a></li>
			@endif
    	
    	@endfor

	    {{-- Next Page Link --}}
        @if ($paging->next_page_url)
            <li><a href="{{ $paging->next_page_url }}" rel="next">@lang('pagination.next')</a></li>
        @else
            <li class="disabled"><span>@lang('pagination.next')</span></li>
        @endif
	</ul>
@endif