routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Route::get('/about-us', 'PagesController@about');
Route::get('/contact-us', 'PagesController@contact');
Route::post('/contact-us', 'PagesController@send_inquiry')->name('contact-us');
Route::get('/terms-of-use', 'PagesController@terms_use');
Route::get('/privacy-policy', 'PagesController@privacy_policy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('logout', function(){
	Auth::logout(); //logout the current user
	Session::flush(); //delete the session
	Cache::flush();
	return Redirect::to('login'); //redirect to login page
})->name('logout');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']] , function(){
	// HomeController Related to profile
	Route::get('/', 'Admin\HomeController@index');	
	Route::get('/dashboard', 'Admin\HomeController@index')->name('dashboard');	
	Route::get('/profile', 'Admin\HomeController@profile')->name('profile');
	Route::post('/profile', 'Admin\HomeController@updateProfile')->name('updateProfile');
	Route::post('/update_email', 'Admin\HomeController@updateEmail');
	Route::get('/update_email', 'Admin\HomeController@updateEmailView')->name('admin_change_email');
	Route::post('/change_password', 'Admin\HomeController@changePassword');
	Route::get('/change_password', 'Admin\HomeController@changePasswordView')->name('admin_change_password');
	
	Route::get('/resetPwd', 'Admin\HomeController@resetPwd');

	// UserController Related to users detail
	Route::resource('user', 'Admin\UserController');
	Route::post('user/update_status', 'Admin\UserController@update_status');

	// EmailController Related to Email template
	Route::resource('email', 'Admin\EmailController');

	// CmsController related to Cms 
	Route::resource('cms', 'Admin\CmsController');
	Route::post('cms/update_status', 'Admin\CmsController@update_status');
	
	Route::get('social', 'Admin\SocialController@index')->name('social');
	Route::post('social', 'Admin\SocialController@update');

	Route::get('company-details', 'Admin\BasicController@view_company_details')->name('company-details');
	Route::delete('company-details', 'Admin\BasicController@update_company_details')->name('update-company-details');
	Route::post('company-details/{type}', 'Admin\BasicController@save_company_details')->name('save-company-details');


	Route::resource('inquiry', 'Admin\InquiryController');
	Route::resource('config','Admin\ConfigurationController',['only' => [
		'index', 'store'
	]]);

	// Testimonials
	Route::resource('testimonials', 'Admin\TestimonialController');
	Route::get('/testimonials/{id}/delete_image', 'Admin\TestimonialController@destroyImage');
	Route::get('/testimonials/update_status/{id}/{status}', [
		'as' => 'testimonial.status',
		'uses' => 'Admin\TestimonialController@updateStatus',
	]);
	Route::delete('/testimonials/destroy/{id}', 'Admin\TestimonialController@destroy');
	Route::post('testimonials/{id}/edit', 'Admin\TestimonialController@update');

});

Route::group(['middleware' => 'auth'] , function(){
	Route::get('/profile', 'ProfileController@index')->name('profile');
	Route::post('/profile-update', 'ProfileController@updateProfile')->name('profile_update');
	Route::get('/change-password', 'ProfileController@changePasswordView');
	Route::post('/change-password', 'ProfileController@changePassword')->name('change-password');
	Route::get('/resetpassword-confirmation', 'ProfileController@confirmResetpassword')->name('checkreset');
});

Route::get('/joinuser/{id}', 'JoinUserController@index');
Route::post('/joinuser/create' , 'JoinUserController@join')->name('joinuser.create');


// to confirm account
Route::get('register/confirm/{user_id}', 'Auth\RegisterController@confirm');
Route::post('register/change-email/{user_id}', 'Auth\RegisterController@changeEmail')->name('change-email');

// to verify email
Route::get('register/verify/{confirmationCode}', 'Auth\VerifyController@verify');
Route::post('register/verify/', 'Auth\VerifyController@verify')->name('register_verify');

Route::get('register/resend/{user_id}', 'Controller@resendVerification')->name('resendverification');

app/Models/UserType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
  	protected $fillable = ['user_id' , 'user_type'];
  	public $timestamps = false;
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Models\UserType;
use App\Models\City;
use App\Models\EmailTemplate;
use Mail;
use Hash;
use Valid;
use EmailProvider;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class UserController extends Controller
{
    protected $userModel;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->userModel     = new User();
        $this->emailprovider = new EmailProvider();

        $this->sortable_columns = [
            0 => 'id',
            1 => 'first_name',
            2 => 'email',
            3 => 'phone',
            4 => 'cities.name',
            5 => 'created_at',
        ];
    }

    /**
     * Show the application manage users.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(Request $request)
    {
        if($request->ajax())
        {
            $totalUser      = User::WhereHas('userType', function($q){
                                $q->where('user_type',"!=" ,'2');
                                })->count();
            $limit          = $request->input('length');
            $start          = $request->input('start');
            $search         = $request['search']['value'];
            $orderby        = $request['order']['0']['column'];
            $order          = $orderby != "" ? $request['order']['0']['dir'] : "";
            $draw           = $request['draw'];

            $response       = $this->userModel->getUserModel($limit, $start, $search, $this->sortable_columns[$orderby], $order);

            if(!$response){
                $users      = [];
                $totalUser     = [];
            }
            else{
                
                $users      = $response->data;
                $totalUser     = $response->total;
            }

            $userData = array();
            $i = 1;
            foreach ($users as $user) {
                $u['DT_RowId']      = $i+$start;
                $u['name']          = $user->first_name . " " . $user->last_name;
                $u['email']         = $user->email;
                $u['phone']         = $user->phone!=NULL ? "(+".$user->phone_code . ")" .$user->phone : '-'; 
                $u['location']      = $user->city!=NULL ? $user->city->name ." , ". $user->city->state . " , ". $user->city->country : '-';
                $u['created_at']    = date('M d, Y' , $user->created_at);

                $user_status        = view('admin.user.status' , ['id' => $user->id , 'status' => $user->status]);
                $u['status']        = $user_status->render();

                $actions            = view('admin.user.actions' , ['id' => $user->id , 'name' => $user->first_name . " " . $user->last_name ]);
                $u['actions']       = $actions->render(); 

                $userData[] = $u;
                $i++;
                unset($u);
            }
            $return = [
                    "draw"              =>  intval($draw),
                    "recordsFiltered"   =>  intval( $totalUser),
                    "recordsTotal"      =>  intval( $totalUser),
                    "data"              =>  $userData
                ];
            return $return;
        }

        $page_title = "Admin | Manage Users";
        return view('admin.user.index')
            ->with('page_title', $page_title);
    }

    /**
     * create to create form for add new user.
     * @return void
    */
    public function create()
    {   
        $data = ["page_title"  => "Admin | Manage User"];
        return view('admin.user.create' , $data);
    }

     /**
     * store to insert new user.
     * @return void
    */
    public function store(Request $request)
    {
        $input = $request->all();
        
        $validator = Validator::make($input,[
            'first_name'  =>  getRule('first_name', true),
            'last_name'   =>  getRule('last_name', false, true),
            'email'       =>  getRule('email', true).'|unique:users',
            'phone'       =>  getRule('phone', false, true),
            'google_id'   =>  getRule('google_id', false, true),
        ]);

        if($validator->fails()) {
            $errors = $validator->errors();
            return back()->withErrors($errors)->withInput();
        }
        else 
        {
            if($input['google_id'] != "")
            {
                $city = City::getCityByGoogleLocation($input);
                $input['city_id']    = $city->id;
            }    
            $input['password']       = bcrypt('user1234');
            $input['phone_code']     = empty($request['phone']) ? null : $input['phone_code'];
            
            // insert into users and usertype 
            $userInfo = User::create($input);
            $userType = UserType::create(['user_id' => $userInfo->id]);

            $user = User::where('id', $userInfo->id)->first();

            // Send join user mail 
            EmailProvider::sendMail('user-join-mail', 
                [
                    'first_name'        => $user->first_name,
                    'last_name'         => $user->last_name,
                    'email'             => $user->email,
                    'url'   => [
                        'join_url'          => '/joinuser/' . encrypt($user->id),
                    ]
                ]
            );

            $message = 'New user '. ucfirst($input['first_name']). ' ' . ucfirst($input['last_name']) . ' added successfully and joining mail is sent successfully to ' . $input['email'] ; 

            $request->session()->flash('alert-success', $message);

            return redirect('admin/user');
        }
    }

    /**
     * destroy to delete user.
     * @return void
    */
    public function destroy(Request $request, $id)
    {
        $id = decrypt( $id );
        try
        {
            $user       = User::findOrFail( $id );
            $first_name = $user->first_name;

            $delete     = $user->delete();
        
            $request->session()->flash('alert-success', 'Record for '.ucfirst($first_name).' deleted successfully.');
            return response(['msg' => 'Content Deleted', 'status' => 'success']); 
        }
        catch(ModelNotFoundException $e){   
           return response(['msg' => 'Failed deleting the content', 'status' => 'failed']);
        }
    }

    /**
     * edit to show user edit.
     * 
     * @return void
     */
    public function edit($id)
    { 
        $user_id = decrypt( $id );

        $user_list = User::with('city')->where('id' , '=', $user_id)->first();
        
        $city = [
            'name'=>'', 'state' =>'', 'country'=>'', 'google_id'=>'', 'place_id'=>''
        ];

        if($user_list->city != NULL) 
        {
            $city['name']       = $user_list->city->name;
            $city['state']      = $user_list->city->state;
            $city['country']    = $user_list->city->country;
            $city['google_id']  = $user_list->city->google_id;
            $city['google_place_id']   = $user_list->city->google_place_id;    
        }

        $data = [
            "page_title"  => "Admin | Settings",
            'user'        => $user_list,
            'city'        => $city   
        ];
        return view('admin.user.edit' , $data);
    }

    /**
     * update to update user.
     * params Request $request , int $id
     * @return void
     */
    public function update(Request $request, $id)
    {
        $id    =  decrypt($id);
        $input = $request->all();

        $validator = Validator::make($input,[
            'first_name'  =>  getRule('first_name', true),
            'last_name'   =>  getRule('last_name', false, true),
            'email'       =>  getRule('email', true).'|unique:users,email,'.$id,
            'phone'       =>  getRule('phone', false, true),
            'google_id'   =>  getRule('google_id', true),
            'zip'         =>  getRule('zip', false, true),
        ]);

        if($validator->fails()) {
            $errors = $validator->errors();
            $request->session()->flash('alert-danger', 'Errors! Please correct the following errors and submit again.');
            return back()->withErrors($errors)->withInput();
        }
        else {
            try {
                $user = User::findOrFail( $id );
                
                if($input['google_id']!="")
                {
                    $city = City::getCityByGoogleLocation($input);
                    $user->city_id     = $city->id;
                }    
                $user->first_name  = $input['first_name'];
                $user->last_name   = $input['last_name'];
                $user->email       = $input['email'];
                $user->username    = $input['username'];
                $user->user_dob    = $input['dob'];
                $user->status      = $input['status'];
                $user->gender      = $input['gender'];
                $user->address_one = $input['address_one'];
                $user->address_two = $input['address_two'];
                $user->zip         = $input['zip'];
                $user->phone_code  = empty($input['phone']) ? null : $input['phone_code']; 
                $user->phone       = $input['phone'];

                $user->save();

                $request->session()->flash('alert-success', 'User ' . ucfirst($user->first_name) . ' ' . ucfirst($user->last_name) .' updated successfully.');
                return redirect('admin/user');
                
            }
            catch(ModelNotFoundException $e){   
                $request->session()->flash('alert-danger', 'Failed to update , Please try again.');
                return redirect()->back();
            }
        }
    }

    /**

resources/views/admin/user/actions.blade.php
<a href="{{ url('admin/user/'.encrypt($id).'/edit') }}" class="btn btn-xs btn-success pencil_anchor" id='{{ encrypt($id) }}'>
<i class="fa fa-pencil"></i>
</a>            

<a href="javascript:void(0)" id='{{"user_".encrypt($id) }}' class='btn btn-xs btn-danger del' data-msg="Are you sure you want to delete this user {{ ucwords($name) }}?"><i class="fa fa-trash"></i></a>

resources/views/admin/user/addform.blade.php
@include('admin.partials.errors')
 
	<form role="form" method="post" enctype="multipart/form-data" class="" action="{{ route('user.store') }}">
	{{ csrf_field() }}
	<div class="box-body">

		<div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
            
	        <label for="fname" class="control-label required">First Name</label>
	        <div>
	        <input id="fname" placeholder="First Name"  type="text" class="form-control" name="first_name" value="{{ old('first_name') }}" maxlength="25" required>

		  	@if ($errors->has('first_name'))
			  	<span class="help-block">
					<strong>{{ $errors->first('first_name') }}</strong>
			  	</span>
		  	@endif
		  	</div>
	    </div>
            
        <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
            <label for="lname" class="control-label">Last Name</label>

            <div>
            <input id="lname"  placeholder="Last Name"  type="text" class="form-control" name="last_name" value="{{ old('last_name') }}" maxlength="25">

		  	@if ($errors->has('last_name'))
			  	<span class="help-block">
					<strong>{{ $errors->first('last_name') }}</strong>
			  	</span>
		  	@endif

		  	</div>
        </div>

        
		<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">

			<label for="email" class=" control-label required">Email</label>
			<div class="">
			  	<input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}"  placeholder="Email" maxlength="100" required>

			  	@if ($errors->has('email'))
				  	<span class="help-block">
						<strong>{{ $errors->first('email') }}</strong>
				  	</span>
			  	@endif

			</div>

		</div>

		<div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
			<label for="tel" class="control-label">Phone Number</label>
		   	<div class="">
		   		<input type="tel" maxlength="15" class="form-control" name="phone" id="phone" value="{{ old('phone') }}" >
		   		 
		   		<input type="hidden" name="phone_code" id="co-code" value="{{ old('phone_code', '1') }}">
		   		<input id="iso2" type="hidden" name="iso2" value="{{ old('iso2') }}">

		   		 @if ($errors->has('phone'))
				  	<span class="help-block">
						<strong>{{ $errors->first('phone') }}</strong>
				  	</span>
			  	@endif
		   	</div>
	    </div>

	    <div class="form-group{{ $errors->has('location') ? ' has-error' : '' }}">
			<label for="location" class="control-label">City/State/Country</label>

			<div class="">
				<div class="geo-details">
					<input type="hidden" name="city" data-geo="locality">
					<input type="hidden" name="state" data-geo="administrative_area_level_1">
					<input type="hidden" name="country" data-geo="country">
				</div>
			  	<input id="city_state_country" type="text" class="form-control" name="location" value="{{ old('location') }}" placeholder="Location">

			  	<input type="hidden" name="place_id" id="google_place_id" value="{{ old('place_id') }}"> 
			  	<input type="hidden" name="google_id" id="google_id" value="{{ old('google_id') }}">  

			  	@if ($errors->has('location'))
				  	<span class="help-block">
						<strong>{{ $errors->first('location') }}</strong>
				  	</span>
			  	@endif
			</div>
		</div>

	 
	<!-- /.box-body -->
	<div class="box-footer">
		<a href="{{ route('user.index') }}" class="btn btn-default">Cancel</a>
		<button type="submit" class="btn btn-info pull-right">Save</button>
	</div>
	<!-- / form -->
</form>

resources/views/admin/user/create.blade.php
@extends('admin.layouts.layout')
@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Users
        <small>Add User</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{!! url('admin/dashboard') !!}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="{!! url('admin/user') !!}">Users</a></li>
        <li class="active"> Add User</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class="row">
        <div class="col-xs-12 col-md-8">
            <div class="box">
                <div class="box-header">
                  <!-- <h3 class="box-title">Hover Data Table</h3> -->
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @include('admin.user.addform')
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        
      </div>
      <!-- /.row -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.layout')
@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Users
        <small>Edit User</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{!! url('admin/dashboard') !!}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="{!! url('admin/user') !!}">Users</a></li>
        <li class="active"> Edit User</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class="row">
        <div class="col-xs-12 col-md-8">
            <div class="box">
                <div class="box-header">
                  <!-- <h3 class="box-title">Hover Data Table</h3> -->
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @include('admin.user.editform')
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        
      </div>
      <!-- /.row -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

resources/views/admin/user/editform.blade.php
@include('admin.partials.errors')

<form role="form" method="post" enctype="multipart/form-data" class="" action="{{ route('user.update', encrypt($user['id'])) }}">

    <input type="hidden" name="_method" value="put" />
	{{ csrf_field() }}
	<div class="box-body">
		<div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
	        <label for="fname" class="control-label required">First Name</label>
	        
            <input id="fname" placeholder="First Name"  type="text" class="form-control" name="first_name" value="{{ old('first_name' , $user['first_name']) }}" maxlength="25" required="">
		  	@if ($errors->has('first_name'))
			  	<span class="help-block">
					<strong>{{ $errors->first('first_name') }}</strong>
			  	</span>
		  	@endif
	    </div>
            
        <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
            <label for="lname" class="control-label">Last Name</label>
           
            <input id="lname"  placeholder="Last Name"  type="text" class="form-control" name="last_name" value="{{ old('last_name' , $user['last_name']) }}" maxlength="25">
		  	@if ($errors->has('last_name'))
			  	<span class="help-block">
					<strong>{{ $errors->first('last_name') }}</strong>
			  	</span>
		  	@endif
        </div>

	    <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
            <label for="username" class="control-label">Username</label>
            
            <input id="username" type="text" class="form-control" name="username" value="{{ old('username' , $user['username']) }}" maxlength="20" placeholder="User Name">
            @if ($errors->has('username'))
                <span class="help-block">
                    <strong>{{ $errors->first('username') }}</strong>
                </span>
            @endif
        </div>

		<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
			<label for="email" class=" control-label required">Email</label>
		  	
            <input id="email" type="email" class="form-control" name="email" value="{{ old('email' , $user['email']) }}"  placeholder="Email" maxlength="100"
            required="">
		  	@if ($errors->has('email'))
			  	<span class="help-block">
					<strong>{{ $errors->first('email') }}</strong>
			  	</span>
		  	@endif
		</div>

		<div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
			<label for="tel" class="control-label">Phone Number</label>

	   		<input type="tel" maxlength="15" class="form-control" name="phone" id="phone" value="{{ old('phone' , $user['phone']) }}" maxlength="12">
	   		 
	   		 <input type="hidden" name="phone_code" id="co-code" value="{{ old('phone_code' , $user['phone_code']) !== null ? $user['phone_code'] : '1' }}">

	   		 @if ($errors->has('phone'))
			  	<span class="help-block">
					<strong>{{ $errors->first('phone') }}</strong>
			  	</span>
		  	@endif
	    </div>

	    <div class="form-group{{ $errors->has('dob') ? ' has-error' : '' }}">
            <label for="dob" class="control-label">Date Of Birth</label> 
            
            <input type="text" class="form-control textRead" placeholder="Date Of Birth" name='dob' id="datepicker" autocomplete="off" value="{{ old('dob' , show_date($user->user_dob)) }}" readonly>

            @if ($errors->has('dob'))
                <span class="help-block">
                    <strong>{{ $errors->first('dob') }}</strong>
                </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
            <label for="gender" class="control-label">Gender</label>
            <select class="form-control" name="gender" id="gender">
                
                @if($user['gender'] == 'u')
                   <option value="u" {{ old('gender') == 'u' || $user['gender'] == "u" ? 'selected' : '' }}>Unspecified</option>
                @endif

                <option value="m" {{ old('gender') == 'm' || $user['gender'] == "m" ? 'selected' : '' }}>Male</option>
                <option value="f" {{ old('gender') == 'f' || $user['gender'] == "f" ? 'selected' : '' }}>Female</option>
                <option value="o" {{ old('gender') == 'o' || $user['gender'] == "o" ? 'selected' : '' }}>Other</option>

            </select>
            @if ($errors->has('gender'))
                <span class="help-block">
                    <strong>{{ $errors->first('gender') }}</strong>
                </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
            <label for="status" class="control-label">Status</label>

            <select name="status" class="form-control">
                @if($user['status'] == 0)
                    <option value="0" {{ old('status') == 0 || $user['status'] == 0 ? 'selected' : '' }} >Pending</option>
                @endif
                <option value="1" {{ old('status') == 1 || $user['status'] == 1 ? 'selected' : '' }}>Active</option>

                <option value="2" {{ old('status') == 2 || $user['status'] == 2 ? 'selected' : '' }}>Inactive</option>
                
                <option value="3" {{ old('status') == 3 || $user['status'] == 3 ? 'selected' : '' }}>Blocked</option>
            </select>
        </div>
            
	    <div class="form-group{{ $errors->has('address_one') ? ' has-error' : '' }}">
            <label for="address_one" class="control-label">Address Line 1</label>
            <input type="text" class="form-control" placeholder="Address Line 1" name='address_one' id="address_one"  value="{{ old('address_one' , $user['address_one']) }}" >
            @if ($errors->has('address_one'))
                <span class="help-block">
                    <strong>{{ $errors->first('address_one') }}</strong>
                </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('address_two') ? ' has-error' : '' }}">
            <label for="address_two" class="control-label">Address Line 2</label>
            <input type="text" class="form-control" placeholder="Address Line 2" name='address_two' id="address_two"  value="{{ old('address_two' , $user['address_two']) }}" >
        
            @if ($errors->has('address_two'))
                <span class="help-block">
                    <strong>{{ $errors->first('address_two') }}</strong>
                </span>
            @endif
        </div>

	    <div class="form-group{{ $errors->has('google_id') ? ' has-error' : '' }}">
			<label for="location" class="control-label required">City/State/Country</label>
			<div class="geo-details">
				<input type="hidden" name="city" data-geo="locality" value="{{ old('city' , $city['name']) }}">

				<input type="hidden" name="state" data-geo="administrative_area_level_1" value="{{ old('state' , $city['state']) }}">
				
                <input type="hidden" name="country" data-geo="country" value="{{ old('country' , $city['country']) }}">
			</div>

		    <input id="city_state_country" type="text" class="form-control" name="location" value="{{ old('location' , 
                                    ($city['name']!=''? 
                                        ($city['name'] == $city['state'] ? 
                                            ($city['name'] . ', ' . $city['country']) : 
                                            ($city['name'] . ', ' . $city['state'] . ', ' . $city['country']
                                        ) 
                                    ) 
                                    : '' )
                                    ) }}" placeholder="Enter a city" maxlength="100">

		  	
		  	<input type="hidden" name="place_id" id="google_place_id" value="{{ old('place_id' , $city['google_place_id']) }}"> 
		  	<input type="hidden" name="google_id" id="google_id" value="{{ old('google_id' , $city['google_id']) }}">  
		  	@if ($errors->has('google_id'))
			  	<span class="help-block">
					<strong>{{ $errors->first('google_id') }}</strong>
			  	</span>
		  	@endif
		</div>

	    <div class="form-group{{ $errors->has('zip') ? ' has-error' : '' }}">
            <label for="zip" class="control-label">Zip Code</label>
            <input type="text" class="form-control" placeholder="Zip Code" name='zip' id="zip"  value="{{ old('zip' , $user['zip']) }}" maxlength="6">
            @if ($errors->has('zip'))
                <span class="help-block">
                    <strong>{{ $errors->first('zip') }}</strong>
                </span>
            @endif
        </div>
        
		<div class="box-footer">
			<a href="{{ route('user.index') }}" class="btn btn-default">Cancel</a>
			<button type="submit" class="btn btn-info pull-right">Save</button>
		</div>
</form>

resources/views/admin/user/status.blade.php
<select name="status" class="form-control userStatus" id={{ encrypt($id)}} >

	@if($status==0)
		<option value="0" {{ old('status', $status) == 0 ? 'selected' : '' }} >Pending</option>
	@endif
	<option value="1" {{ old('status', $status) == 1 ? 'selected' : '' }}>Active</option>
	<option value="2" {{ old('status', $status) == 2 ? 'selected' : '' }}>Inactive</option>
	<option value="3" {{ old('status', $status) == 3 ? 'selected' : '' }}>Blocked</option>

</select>